# Generated by Django 5.2.4 on 2025-07-29 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortraitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('portrait_type', models.CharField(choices=[('Pencil', 'Pencil'), ('Color', 'Color'), ('Couple', 'Couple'), ('Wedding', 'Wedding Gift')], max_length=20)),
                ('size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2')], max_length=10)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='reference_images/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
