# Generated by Django 5.2.4 on 2025-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_portraitorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LovedSketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='loved_sketches/')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
    ]
