# Generated by Django 5.2.4 on 2025-07-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LovedSketch',
        ),
    ]
