# Generated by Django 5.2.4 on 2025-07-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='No comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
