# Generated by Django 5.2.4 on 2025-07-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0004_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
