# Generated by Django 5.2.4 on 2025-07-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0007_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPortrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='featured/')),
                ('size', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FevPortrait',
        ),
    ]
