# Generated by Django 5.2.4 on 2025-07-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0008_featuredportrait_delete_fevportrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredportrait',
            name='image',
            field=models.ImageField(upload_to='portraits/'),
        ),
    ]
