# Generated by Django 5.2.4 on 2025-07-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(upload_to='orders/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='portrait_type',
            field=models.CharField(choices=[('pencil', 'Pencil Sketch'), ('color', 'Color Portrait'), ('couple', 'Couple Portrait'), ('wedding', 'Wedding Gift')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2')], max_length=10),
        ),
    ]
